title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

title: <p align="center"> Kaushal Yadav </p>
logo: /assets/img/Kaushal_new.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/kaushal012/">LinkedIn</a> |
  <a href="https://github.com/data-KY">GitHub</a>
  
  <br>   
  I'm working on Data Science
  <br>
  </p>



theme: jekyll-theme-minimal
